language: python
python:
  - 2.6
  - 2.7
  - 3.5
# command to install dependencies
before_install:
  - pip install pytest-cov
install:
  - cd src
  - python setup.py install
# command to run tests
script: py.test cmdtree --cov=cmdtree